.TH "C:/Users/Stagiaire/Documents/VisualStudio[source]/DB_Projet_Active/DB_Projet_Active Directory Reference" 3 "Mon Jan 7 2019" "Version 0.1" "Projet_Active_c#" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Stagiaire/Documents/VisualStudio[source]/DB_Projet_Active/DB_Projet_Active Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBobj\fP"
.br
.ti -1c
.RI "directory \fBProperties\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAccueil\&.cs\fP"
.br
.ti -1c
.RI "file \fBAccueil\&.Designer\&.cs\fP"
.br
.ti -1c
.RI "file \fBClient\&.cs\fP"
.br
.ti -1c
.RI "file \fBCreaClient\&.cs\fP"
.br
.ti -1c
.RI "file \fBCreaClient\&.Designer\&.cs\fP"
.br
.ti -1c
.RI "file \fBEcranGestion\&.cs\fP"
.br
.ti -1c
.RI "file \fBEcranGestion\&.Designer\&.cs\fP"
.br
.ti -1c
.RI "file \fBFonctionSQL\&.cs\fP"
.br
.ti -1c
.RI "file \fBFormulaire\&.cs\fP"
.br
.ti -1c
.RI "file \fBFormulaire\&.Designer\&.cs\fP"
.br
.ti -1c
.RI "file \fBProgram\&.cs\fP"
.br
.ti -1c
.RI "file \fBProspect\&.cs\fP"
.br
.in -1c
