.TH "C:/Users/Stagiaire/Documents/VisualStudio[source]/DB_Projet_Active/DB_Projet_Active/Properties Directory Reference" 3 "Mon Jan 7 2019" "Version 0.1" "Projet_Active_c#" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Stagiaire/Documents/VisualStudio[source]/DB_Projet_Active/DB_Projet_Active/Properties Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAssemblyInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBResources\&.Designer\&.cs\fP"
.br
.ti -1c
.RI "file \fBSettings\&.Designer\&.cs\fP"
.br
.in -1c
