.TH "DB_Projet_Active.Properties.Resources" 3 "Mon Jan 7 2019" "Version 0.1" "Projet_Active_c#" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DB_Projet_Active.Properties.Resources \- Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées\&. 



.SH "Author"
.PP 
Generated automatically by Doxygen for Projet_Active_c# from the source code\&.
