.TH "DB_Projet_Active" 3 "Mon Jan 7 2019" "Version 0.1" "Projet_Active_c#" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DB_Projet_Active
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBProperties\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAccueil\fP"
.br
.RI "La Class \fBAccueil\fP qui est l entree de l application et contient les methodes pour choisir si l on veut travailler sur les CLIENTS ou les PROSPECTS "
.ti -1c
.RI "class \fBClient\fP"
.br
.ti -1c
.RI "class \fBCreaClient\fP"
.br
.ti -1c
.RI "class \fBEcranGestion\fP"
.br
.RI "La Class \fBEcranGestion\fP qui affiche, dans un DataGridView, en fonction du choix a l ecran d accueil et la liste des CLIENTS ou des PROSPECTS\&. Contient les methodes pour charger le DataGridView, et les differents boutons (ajouter, mettre a jour, supprimer et retour) "
.ti -1c
.RI "class \fBFonctionSQL\fP"
.br
.ti -1c
.RI "class \fBFormulaire\fP"
.br
.RI "La Class \fBFormulaire\fP qui affiche, dans des TextBox, DateTimePicker et CheckBox, les informations concernant la creation ou la mise a jour des CLIENTS ou des PROSPECTS\&. Contient les methodes pour controler la saisie, et les differents boutons (valider et retour) "
.ti -1c
.RI "class \fBProgram\fP"
.br
.ti -1c
.RI "class \fBProspect\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Projet_Active_c# from the source code\&.
