.TH "DB_Projet_Active.Accueil" 3 "Mon Jan 7 2019" "Version 0.1" "Projet_Active_c#" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DB_Projet_Active.Accueil \- La Class \fBAccueil\fP qui est l entree de l application et contient les methodes pour choisir si l on veut travailler sur les CLIENTS ou les PROSPECTS  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAccueil\fP ()"
.br
.RI "Initialisation de tous les composants de la Class \fBAccueil\fP "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Nettoyage des ressources utilisées\&. "
.in -1c
.SH "Detailed Description"
.PP 
La Class \fBAccueil\fP qui est l entree de l application et contient les methodes pour choisir si l on veut travailler sur les CLIENTS ou les PROSPECTS 

Auteur : Franck Jakubowski
.PP
Version : 0\&.1
.PP
Date de creation : 07/01/2019
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DB_Projet_Active\&.Accueil\&.Accueil ()"

.PP
Initialisation de tous les composants de la Class \fBAccueil\fP 
.SH "Member Function Documentation"
.PP 
.SS "override void DB_Projet_Active\&.Accueil\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Nettoyage des ressources utilisées\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdisposing\fP true si les ressources managées doivent être supprimées ; sinon, false\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Projet_Active_c# from the source code\&.
