.TH "C:/Users/Stagiaire/Documents/VisualStudio[source]/DB_Projet_Active/DB_Projet_Active/Formulaire.Designer.cs" 3 "Mon Jan 7 2019" "Version 0.1" "Projet_Active_c#" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Stagiaire/Documents/VisualStudio[source]/DB_Projet_Active/DB_Projet_Active/Formulaire.Designer.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDB_Projet_Active\&.Formulaire\fP"
.br
.RI "La Class \fBFormulaire\fP qui affiche, dans des TextBox, DateTimePicker et CheckBox, les informations concernant la creation ou la mise a jour des CLIENTS ou des PROSPECTS\&. Contient les methodes pour controler la saisie, et les differents boutons (valider et retour) "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDB_Projet_Active\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Projet_Active_c# from the source code\&.
