.TH "Properties Directory Reference" 3 "Mon Apr 1 2019" "Version 0.1" "Projet_Active_c#" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Properties Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAssemblyInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBResources\&.Designer\&.cs\fP"
.br
.ti -1c
.RI "file \fBSettings\&.Designer\&.cs\fP"
.br
.in -1c
