.TH "Client.cs" 3 "Mon Apr 1 2019" "Version 0.1" "Projet_Active_c#" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Client.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDB_Projet_Active\&.Client\fP"
.br
.RI "La Class \fBClient\fP qui permet d instancier des Clients\&. Contient les methodes pour generer la liste de client, creer, mettre a jour et supprimer un client "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDB_Projet_Active\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Projet_Active_c# from the source code\&.
