.TH "DB_Projet_Active.Properties.Settings" 3 "Mon Apr 1 2019" "Version 0.1" "Projet_Active_c#" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DB_Projet_Active.Properties.Settings
.SH SYNOPSIS
.br
.PP
.PP
Inherits ApplicationSettingsBase\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBSettings\fP \fBDefault\fP\fC [get]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\fBSettings\fP DB_Projet_Active\&.Properties\&.Settings\&.Default\fC [static]\fP, \fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Projet_Active_c# from the source code\&.
