.TH "DB_Projet_Active.CreaClient" 3 "Mon Apr 1 2019" "Version 0.1" "Projet_Active_c#" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DB_Projet_Active.CreaClient
.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCreaClient\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DB_Projet_Active\&.CreaClient\&.CreaClient ()"

.SH "Member Function Documentation"
.PP 
.SS "override void DB_Projet_Active\&.CreaClient\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Projet_Active_c# from the source code\&.
