.TH "EcranGestion.Designer.cs" 3 "Mon Apr 1 2019" "Version 0.1" "Projet_Active_c#" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EcranGestion.Designer.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDB_Projet_Active\&.EcranGestion\fP"
.br
.RI "La Class \fBEcranGestion\fP qui affiche, dans un DataGridView, en fonction du choix a l ecran d accueil et la liste des CLIENTS ou des PROSPECTS\&. Contient les methodes pour charger le DataGridView, et les differents boutons (ajouter, mettre a jour, supprimer et retour) "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDB_Projet_Active\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Projet_Active_c# from the source code\&.
